export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL'
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED'

export const CREATE_TODO = 'CREATE_TODO'
export const GET_TODO = 'GET_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const SETUP_TODOLIST = 'SETUP_TODOLIST'
export const FEILED_CREATE_TODO = 'FEILED_CREATE_TODO'



export const REGISTRATION = 'REGISTRATION'
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'