export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTRATION = 'REGISTRATION'
export const SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const FAILED = 'LOGIN_FAILED'
export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL'
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED'